# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XD-8qYYze6SW_3QQz-5X6t_xLN8hszOw
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go

# =====================================================
# CONFIG
# =====================================================
st.set_page_config(
    page_title="Student Performance Dashboard",
    page_icon="🎓",
    layout="wide"
)

# =====================================================
# LOAD DATA
# =====================================================
@st.cache_data
def load_data():
    df = pd.read_csv("student_performance_grade.csv")
    return df

df = load_data()

# =====================================================
# TITLE
# =====================================================
st.title("🎓 Student Performance Dashboard")
st.markdown(
    """
Dashboard ini menampilkan analisis data performa mahasiswa
berdasarkan berbagai faktor seperti jam belajar, kehadiran,
GPA, tingkat stres, screen time, metode belajar, dan grade.
"""
)

st.divider()

# =====================================================
# SIDEBAR
# =====================================================
st.sidebar.title("Dashboard Filter")

gender = st.sidebar.multiselect(
    "Gender",
    sorted(df["Gender"].unique()),
    default=sorted(df["Gender"].unique())
)

grade = st.sidebar.multiselect(
    "Grade",
    sorted(df["Grade"].unique()),
    default=sorted(df["Grade"].unique())
)

study_method = st.sidebar.multiselect(
    "Study Method",
    sorted(df["Study_Method"].unique()),
    default=sorted(df["Study_Method"].unique())
)

parttime = st.sidebar.multiselect(
    "Part Time Job",
    sorted(df["Part_Time_Job"].unique()),
    default=sorted(df["Part_Time_Job"].unique())
)

df = df[
    (df["Gender"].isin(gender)) &
    (df["Grade"].isin(grade)) &
    (df["Study_Method"].isin(study_method)) &
    (df["Part_Time_Job"].isin(parttime))
]

# =====================================================
# KPI
# =====================================================
st.subheader("Ringkasan Data")

kpi1, kpi2, kpi3, kpi4 = st.columns(4)

kpi1.metric(
    "Jumlah Mahasiswa",
    len(df)
)

kpi2.metric(
    "Rata-rata GPA",
    round(df["Previous_GPA"].mean(),2)
)

kpi3.metric(
    "Jam Belajar",
    round(df["Hours_Studied"].mean(),2)
)

kpi4.metric(
    "Kehadiran",
    f"{df['Attendance'].mean():.1f}%"
)

st.divider()

# =====================================================
# ROW 1
# =====================================================
col1, col2 = st.columns(2)

with col1:

    st.subheader("Distribusi Grade")

    grade_count = (
        df["Grade"]
        .value_counts()
        .reset_index()
    )

    grade_count.columns = ["Grade","Jumlah"]

    fig = px.bar(
        grade_count,
        x="Grade",
        y="Jumlah",
        color="Grade",
        text="Jumlah",
        template="plotly_white"
    )

    fig.update_layout(
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

with col2:

    st.subheader("Komposisi Gender")

    fig = px.pie(
        df,
        names="Gender",
        hole=0.45,
        template="plotly_white"
    )

    fig.update_layout(
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

st.divider()
# =====================================================
# ROW 2
# =====================================================
col3, col4 = st.columns(2)

with col3:

    st.subheader("Distribusi Jam Belajar")

    fig = px.histogram(
        df,
        x="Hours_Studied",
        nbins=25,
        color_discrete_sequence=["#4F46E5"],
        template="plotly_white"
    )

    fig.update_layout(
        xaxis_title="Hours Studied",
        yaxis_title="Jumlah Mahasiswa",
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

with col4:

    st.subheader("Jam Belajar vs Previous GPA")

    fig = px.scatter(
        df,
        x="Hours_Studied",
        y="Previous_GPA",
        color="Grade",
        size="Attendance",
        hover_name="Student_ID",
        template="plotly_white"
    )

    fig.update_layout(
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

st.divider()

# =====================================================
# ROW 3
# =====================================================
col5, col6 = st.columns(2)

with col5:

    st.subheader("Attendance Berdasarkan Grade")

    fig = px.box(
        df,
        x="Grade",
        y="Attendance",
        color="Grade",
        template="plotly_white"
    )

    fig.update_layout(
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

with col6:

    st.subheader("Distribusi Metode Belajar")

    study = (
        df["Study_Method"]
        .value_counts()
        .reset_index()
    )

    study.columns = [
        "Study_Method",
        "Jumlah"
    ]

    fig = px.bar(
        study,
        x="Study_Method",
        y="Jumlah",
        color="Study_Method",
        text="Jumlah",
        template="plotly_white"
    )

    fig.update_layout(
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

st.divider()

# =====================================================
# ROW 4
# =====================================================
col7, col8 = st.columns(2)

with col7:

    st.subheader("Status Part Time Job")

    fig = px.pie(
        df,
        names="Part_Time_Job",
        hole=0.45,
        template="plotly_white"
    )

    fig.update_layout(
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

with col8:

    st.subheader("Diet Quality")

    diet = (
        df["Diet_Quality"]
        .value_counts()
        .reset_index()
    )

    diet.columns = [
        "Diet",
        "Jumlah"
    ]

    fig = px.bar(
        diet,
        x="Diet",
        y="Jumlah",
        color="Diet",
        text="Jumlah",
        template="plotly_white"
    )

    fig.update_layout(
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

st.divider()
# =====================================================
# ROW 5
# =====================================================
col9, col10 = st.columns(2)

with col9:

    st.subheader("Screen Time vs Stress Level")

    fig = px.scatter(
        df,
        x="Screen_Time",
        y="Stress_Level",
        color="Grade",
        size="Hours_Studied",
        hover_name="Student_ID",
        template="plotly_white"
    )

    fig.update_layout(
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

with col10:

    st.subheader("Internet Quality")

    internet = (
        df["Internet_Quality"]
        .value_counts()
        .reset_index()
    )

    internet.columns = [
        "Internet",
        "Jumlah"
    ]

    fig = px.bar(
        internet,
        x="Internet",
        y="Jumlah",
        color="Internet",
        text="Jumlah",
        template="plotly_white"
    )

    fig.update_layout(
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

st.divider()

# =====================================================
# ROW 6
# =====================================================
col11, col12 = st.columns(2)

with col11:

    st.subheader("Extracurricular Activity")

    extra = (
        df["Extracurricular"]
        .value_counts()
        .reset_index()
    )

    extra.columns = [
        "Extracurricular",
        "Jumlah"
    ]

    fig = px.bar(
        extra,
        x="Extracurricular",
        y="Jumlah",
        color="Extracurricular",
        text="Jumlah",
        template="plotly_white"
    )

    fig.update_layout(
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

with col12:

    st.subheader("Family Income Level")

    income = (
        df["Family_Income_Level"]
        .value_counts()
        .reset_index()
    )

    income.columns = [
        "Income",
        "Jumlah"
    ]

    fig = px.pie(
        income,
        names="Income",
        values="Jumlah",
        hole=0.45,
        template="plotly_white"
    )

    fig.update_layout(
        height=420
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

st.divider()

# =====================================================
# HEATMAP
# =====================================================
st.subheader("Heatmap Korelasi")

numeric = df.select_dtypes(include="number")

corr = numeric.corr().round(2)

fig = ff.create_annotated_heatmap(
    z=corr.values,
    x=list(corr.columns),
    y=list(corr.index),
    annotation_text=corr.values,
    colorscale="Viridis",
    showscale=True
)

fig.update_layout(
    height=700
)

st.plotly_chart(
    fig,
    use_container_width=True
)

st.divider()

# =====================================================
# STATISTIK DESKRIPTIF
# =====================================================
st.subheader("Statistik Deskriptif")

st.dataframe(
    df.describe(),
    use_container_width=True
)

st.divider()

# =====================================================
# PREVIEW DATASET
# =====================================================
st.subheader("Dataset")

st.dataframe(
    df,
    use_container_width=True,
    height=450
)

st.divider()

# =====================================================
# DOWNLOAD CSV
# =====================================================
csv = df.to_csv(index=False).encode("utf-8")

st.download_button(
    label="⬇ Download Dataset",
    data=csv,
    file_name="student_performance_grade.csv",
    mime="text/csv"
)

st.divider()